<div id="clara-embed" style="height:500px">
  <div id="panelControl"></div>
  <div id="panel-embed"></div>
</div>
<script>
  require([
    'claraplayer'
  ], function(player){
      var clara = player('clara-embed');
      clara.on('loaded', function() {
        console.log('Clara player is loaded and ready');
      });

      // Fetch and initialize the sceneId
      clara.sceneIO.fetchAndUse("6cfce43b-fd40-4624-bee6-7f911e9405dd");
  });
</script>
