<div id="clara-embed" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
  <div id="panelControl"></div>
  <div id="panel-embed"></div>
</div>
<script>
  require(["claraplayer"], function(){
    var clara = claraplayer('clara-embed');

    clara.on('loaded', function() {
      console.log('Clara player is loaded and ready');
    });

    // Fetch and initialize the sceneId
    clara.sceneIO.fetchAndUse("6cfce43b-fd40-4624-bee6-7f911e9405dd");
  });
</script>
