<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()):?>
      <div class="" data-role="clara-panelControl" id="clara-panelControl" />
      <script type="text/x-magento-init">
        {
          "[data-role=clara-panelControl]": {
            "js/clara-configurator": {
              "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>
            }
          }
        }
      </script>
<?php endif;?>


